### ISSUE TITLE
Clicking the label above the "Foo Bar" soft locks game.

### ISSUE THREAD

**Issue by Moto42** [ByteLegend/ByteLegend#129]
Clicking the door to the FooBar allows character to enter as normal.

Clicking the label above the bar has the character walk into the door, then after the screen transition
the player character is not on screen.

Clicking the door to leave does nothing. I assume screen transitions are tied to the character colliding with a tile? So without the character to move, you are trapped on this screen. Just guessing.

Was running in Firefox Developer Edition v 100.0b5

**Comment by blindpirate** [comment]
Hi @Moto42 , this is by design. The idea is that you can browse another map/dungeon/island by clicking the the label, even when your character is not able to walk there.

> Clicking the label above the bar has the character walk into the door, then after the screen transition
the player character is not on screen.
> Clicking the door to leave does nothing. I assume screen transitions are tied to the character colliding with a tile? So without the character to move, you are trapped on this screen. Just guessing.

That's correct. In this mode, clicking the door doesn't mean "leave". You can see the mouse cursor color: green means walkable, red means not walkable, white means "hero is not in the scene". You have to click the "hero iindicator" to switch scene:

<img width="313" alt="image" src="https://user-images.githubusercontent.com/12689835/163281925-c723b7f3-4bda-416c-8ac7-ac67bc1e349e.png">

You are not the first one having this question. I wonder how the UX design can be better.
